app/views/job.py
from app import db
from app.forms import JobForm
from app.models import Job, OptIn

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import datetime

job = Blueprint('job', __name__, url_prefix='/job/', template_folder='templates')


@job.route('/', methods=['GET', 'POST'])
@login_required
def index():
    job_form = JobForm()

    if job_form.validate_on_submit():
        if job_form.date.data.weekday() == 6:
            flash('Date cannot fall on a Sunday.', 'danger')
            return redirect(url_for('job.index'))

        new_job = Job(user_id=current_user.id,
                      address=job_form.address.data,
                      date=job_form.date.data,
                      time=job_form.time.data,
                      notes=job_form.notes.data)

        db.session.add(new_job)
        db.session.commit()

        flash('Job created successfully.', 'success')
        return redirect(url_for('job.index'))

    data = {
        'editing': False,
        'title': 'Jobs',
        'form': job_form,
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'past_jobs': Job.query.filter(Job.date < datetime.date.today()).order_by(Job.date).all()
    }

    return render_template('job/index.html', **data)


@job.route('/<int:job_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    job_form = JobForm(obj=this_job)

    if job_form.validate_on_submit():
        job_form.populate_obj(this_job)
        db.session.commit()

        flash('Job edited.', 'success')
        return redirect(url_for('job.index'))

    return render_template('job/index.html', editing=True, title='Edit Job', form=job_form)


@job.route('/<int:job_id>/cancel/')
@login_required
def cancel(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    this_job.cancelled = not this_job.cancelled
    db.session.commit()

    if this_job.cancelled:
        flash('Job cancelled.', 'success')
    else:
        flash('Job un-cancelled.', 'success')

    return redirect(url_for('job.index'))


@job.route('/<int:job_id>/feedback/')
@login_required
def feedback(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_feedback = this_job.get_feedback(job_id)

    return render_template('job/feedback.html', title='Feedback For Address', job=this_job, all_feedback=all_feedback)


@job.route('/<int:job_id>/opt-in/')
@login_required
def opt_in(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    if this_job.cancelled:
        flash('Cannot opt-into/opt-out of a cancelled job.', 'danger')
        return redirect(url_for('user.roster'))

    this_opt_in = OptIn.query.filter_by(job_id=job_id, user_id=current_user.id).scalar()

    if this_opt_in:
        db.session.delete(this_opt_in)
        db.session.commit()

        flash('Opted-out.', 'success')
        return redirect(url_for('user.roster'))

    new_opt_in = OptIn(job_id=job_id, user_id=current_user.id)

    db.session.add(new_opt_in)
    db.session.commit()

    flash('Opted-in.', 'success')
    return redirect(url_for('user.roster'))


@job.route('/<int:job_id>/opt-ins/')
@login_required
def opt_ins(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_opt_ins = this_job.get_opt_ins(job_id)

    return render_template('job/opt_ins.html', title='Job #' + str(job_id) + ' Opt-ins', opt_ins=all_opt_ins)

app/views/news.py
from app import db
from app.forms import NewsForm
from app.models import NewsItem, NewsItemAcknowledgement

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required

news = Blueprint('news', __name__, url_prefix='/news/', template_folder='templates')


@news.route('/', methods=['GET', 'POST'])
@login_required
def index():
    news_form = NewsForm()

    if news_form.validate_on_submit():
        new_news = NewsItem(user_id=current_user.id, title=news_form.title.data, body=news_form.body.data)

        db.session.add(new_news)
        db.session.commit()

        flash('News item posted.', 'success')
        return redirect(url_for('news.index'))

    news_items = NewsItem.query.order_by(NewsItem.created_at).all()

    data = {
        'editing': False,
        'title': 'News',
        'form': news_form,
        'news_items': news_items
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    news_form = NewsForm(obj=news_item)

    if news_form.validate_on_submit():
        news_form.populate_obj(news_item)
        db.session.commit()

        flash('News item edited.', 'success')
        return redirect(url_for('news.index'))

    data = {
        'editing': True,
        'title': 'Edit News Item',
        'form': news_form,
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/delete/')
@login_required
def delete(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    db.session.delete(news_item)
    db.session.commit()

    flash('News item deleted.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledge/')
@login_required
def acknowledge(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    if news_item.is_acknowledged(current_user.id):
        flash('News item already acknowledged.', 'danger')
        return redirect(url_for('news.index'))

    new_acknowledgement = NewsItemAcknowledgement(user_id=current_user.id, news_item_id=news_item_id)

    db.session.add(new_acknowledgement)
    db.session.commit()

    flash('News item acknowledged.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledgements/', methods=['GET', 'POST'])
@login_required
def acknowledgements(news_item_id):
    all_acknowledgements = NewsItemAcknowledgement.query.filter_by(news_item_id=news_item_id).order_by(NewsItemAcknowledgement.created_at).all()

    data = {
        'acknowledgements': all_acknowledgements,
        'title': 'News Item #' + str(news_item_id) + ' Acknowledgments'
    }

    return render_template('news/acknowledgements.html', **data)

app/templates/job/_list.html
<div class="card mb-3">
    <div class="card-header"><strong>Created by:</strong> {{ job.author.full_name }} on {{ timestamp_pretty(job.created_at) }}</div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong class="text-dark">Address:</strong> {{ job.address }}</li>
        <li class="list-group-item"><strong class="text-dark">Date:</strong> {{ timestamp_pretty(job.date, show_time=False) }}</li>
        <li class="list-group-item"><strong class="text-dark">Time:</strong> {{ job.time }}</li>
        {% if job.notes %}
            <li class="list-group-item"><strong class="text-dark">Notes:</strong> {{ job.notes }}</li>
        {% endif %}
        <div class="list-group-item">
            {% with n_opt_ins = job.get_opt_ins(job.id)|length %}
                {% if n_opt_ins > 0 %}
                    <a href="{{ url_for('job.opt_ins', job_id=job.id) }}" class="btn btn-primary">View {{ n_opt_ins }} opt-in(s)</a>
                {% else %}
                    <button class="btn btn-secondary" disabled>No opt-ins</button>
                {% endif %}
            {% endwith %}
            {% with n_feedback = job.get_feedback(job.id)|length %}
                {% if n_feedback > 0 %}
                    <a href="{{ url_for('job.feedback', job_id=job.id) }}" class="btn btn-primary">View {{ n_feedback }} feedback</a>
                {% else %}
                    <button class="btn btn-secondary" disabled>No feedback</button>
                {% endif %}
            {% endwith %}
            {% if not past_job %}
                <div class="btn-group float-right" role="group">
                    <a href="{{ url_for('job.edit', job_id=job.id) }}" class="btn btn-warning">Edit</a>
                    <a href="{{ url_for('job.cancel', job_id=job.id) }}" class="btn btn-danger">{{ 'Un-c' if job.cancelled else 'C' }}ancel Job</a>
                </div>
            {% endif %}
        </div>
    </ul>
</div>

app/templates/job/feedback.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5">
        <div class="card-header"><strong>Created by:</strong> {{ job.author.full_name }} on {{ timestamp_pretty(job.created_at) }}</div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong class="text-dark">Address:</strong> {{ job.address }}</li>
            <li class="list-group-item"><strong class="text-dark">Date:</strong> {{ timestamp_pretty(job.date, show_time=False) }}</li>
            <li class="list-group-item"><strong class="text-dark">Time:</strong> {{ job.time }}</li>
            {% if job.notes %}
                <li class="list-group-item"><strong class="text-dark">Notes:</strong> {{ job.notes }}</li>
            {% endif %}
        </ul>
    </div>
    <h2 class="mb-3">
        <a href="{{ url_for('job.index') }}" class="btn btn-primary btn-lg">◄ Back to Jobs</a>
        Feedback ({{ all_feedback|length }})
    </h2>
    {% for feedback in all_feedback %}
        <div class="card mb-3">
            <div class="card-body">
                <h3>{{ feedback.author.full_name }}</h3>
                <p><i>Posted on {{ timestamp_pretty(feedback.created_at) }}</i></p>
                <hr>
                {{ feedback.body }}
            </div>
        </div>
    {% else %}
        <p>No feedback to show right now.</p>
    {% endfor %}
{% endblock %}

app/templates/job/form.html
<div class="card mb-5 bg-light">
    <div class="card-header">
        <h2 class="mb-3">{{ 'Edit' if editing else 'New' }} Job</h2>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                {{ form.address.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.address(class_='form-control') }}
                    {% for error in form.address.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.date.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.date(class_='form-control') }}
                    {% for error in form.date.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.time.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.time(class_='form-control') }}
                    {% for error in form.time.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.notes.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.notes(class_='form-control') }}
                    {% for error in form.notes.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            {% if editing %}
                {{ form.submit(class_='btn btn-primary float-right', value='Save Changes') }}
                <a href="{{ url_for('job.index') }}" class="btn btn-warning">Discard Changes</a>
            {% else %}
                {{ form.submit(class_='btn btn-primary float-right') }}
            {% endif %}
        </form>
    </div>
</div>

app/templates/job/index.html
{% extends "_base.html" %}

{% block content %}
    {% include '_forms/job.html' %}
    {% if not editing %}
        <h2 class="mb-3">Current Jobs ({{ current_jobs|length }})</h2>
        {% for job in current_jobs %}
            {% include 'job/_list.html' %}
        {% else %}
            <p>No current jobs.</p>
        {% endfor %}
        <h2 class="mt-5 mb-3">Past Jobs ({{ past_jobs|length }})</h2>
        {% for job in past_jobs %}
            {% with past_job = True %}
                {% include 'job/_list.html' %}
            {% endwith %}
        {% else %}
            <p>No past jobs.</p>
        {% endfor %}
    {% endif %}
{% endblock %}

app/templates/job/list.html
<div class="card mb-3">
    <div class="card-header"><strong>Created by:</strong> {{ job.author.full_name }} on {{ timestamp_pretty(job.created_at) }}</div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong class="text-dark">Address:</strong> {{ job.address }}</li>
        <li class="list-group-item"><strong class="text-dark">Date:</strong> {{ timestamp_pretty(job.date, show_time=False) }}</li>
        <li class="list-group-item"><strong class="text-dark">Time:</strong> {{ job.time }}</li>
        {% if job.notes %}
            <li class="list-group-item"><strong class="text-dark">Notes:</strong> {{ job.notes }}</li>
        {% endif %}
        <div class="list-group-item">
            {% with n_opt_ins = job.get_opt_ins(job.id)|length %}
                {% if n_opt_ins > 0 %}
                    <a href="{{ url_for('job.opt_ins', job_id=job.id) }}" class="btn btn-primary">View {{ n_opt_ins }} opt-in(s)</a>
                {% else %}
                    <button class="btn btn-secondary" disabled>No opt-ins</button>
                {% endif %}
            {% endwith %}
            {% with n_feedback = job.get_feedback(job.id)|length %}
                {% if n_feedback > 0 %}
                    <a href="{{ url_for('job.feedback', job_id=job.id) }}" class="btn btn-primary">View {{ n_feedback }} feedback</a>
                {% else %}
                    <button class="btn btn-secondary" disabled>No feedback</button>
                {% endif %}
            {% endwith %}
            {% if not past_job %}
                <div class="btn-group float-right" role="group">
                    <a href="{{ url_for('job.edit', job_id=job.id) }}" class="btn btn-warning">Edit</a>
                    <a href="{{ url_for('job.cancel', job_id=job.id) }}" class="btn btn-danger">{{ 'Un-c' if job.cancelled else 'C' }}ancel Job</a>
                </div>
            {% endif %}
        </div>
    </ul>
</div>

app/templates/job/new.html
<div class="card mb-5 bg-light">
    <div class="card-header">
        <h2 class="mb-3">{{ 'Edit' if editing else 'New' }} Job</h2>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                {{ form.address.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.address(class_='form-control') }}
                    {% for error in form.address.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.date.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.date(class_='form-control') }}
                    {% for error in form.date.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.time.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.time(class_='form-control') }}
                    {% for error in form.time.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.notes.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.notes(class_='form-control') }}
                    {% for error in form.notes.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            {% if editing %}
                {{ form.submit(class_='btn btn-primary float-right', value='Save Changes') }}
                <a href="{{ url_for('job.index') }}" class="btn btn-warning">Discard Changes</a>
            {% else %}
                {{ form.submit(class_='btn btn-primary float-right') }}
            {% endif %}
        </form>
    </div>
</div>

app/templates/job/opt_in.html
{% extends "base.html" %}

{% block content %}
    <h2 class="mb-3">Opt-ins ({{ opt_ins|length }})
        <a href="{{ url_for('job.index') }}" class="btn btn-primary btn-lg">Back to Jobs</a></h2>
    {% for opt_in in opt_ins %}
        <div class="card mb-3">
            <div class="card-body">
                ✅ {{ opt_in.opter.full_name }} opted in on {{ timestamp_pretty(opt_in.created_at) }}
            </div>
        </div>
    {% else %}
        <p>No opt-ins yet.</p>
    {% endfor %}
{% endblock %}

app/templates/job/opt_ins.html
{% extends "_base.html" %}

{% block content %}
    <h2 class="mb-3">
        <a href="{{ url_for('job.index') }}" class="btn btn-primary btn-lg mr-1"">◄ Back to Jobs</a>
        Opt-ins ({{ opt_ins|length }})
    </h2>
    {% for opt_in in opt_ins %}
        <div class="card mb-3">
            <div class="card-body">
                ✅ {{ opt_in.opter.full_name }} opted in on {{ timestamp_pretty(opt_in.created_at) }}
            </div>
        </div>
    {% else %}
        <p>No opt-ins yet.</p>
    {% endfor %}
{% endblock %}