app/views/auth.py
from app import db
from app.forms import RegistrationForm, LoginForm
from app.models import User, Invite

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import login_user, current_user, logout_user

auth = Blueprint('auth', __name__, template_folder='templates')


@auth.route('/register/<invite_key>', methods=['GET', 'POST'])
def register(invite_key):
    if current_user.is_authenticated:
        flash('You are already logged in.', 'info')
        return redirect(url_for('user.dashboard'))

    invite = Invite.query.filter_by(key=invite_key).scalar()

    if not invite:
        abort(404)

    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():
        invite.user.set_password(registration_form.password.data)

        db.session.delete(invite)
        db.session.commit()

        login_user(invite.user)
        flash('Registration successful.', 'success')
        return redirect(url_for('user.dashboard'))

    data = {
        'title': 'Register',
        'form': registration_form,
        'user': invite.user
    }

    return render_template('auth/register.html', **data)


@auth.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in.', 'info')
        return redirect(url_for('user.dashboard'))

    login_form = LoginForm()

    if login_form.validate_on_submit():
        this_user = User.query.filter_by(email=login_form.email.data).scalar()

        if this_user is None or not this_user.check_password(login_form.password.data):
            flash('Invalid credentials.', 'danger')
            return redirect(url_for('auth.login'))

        login_user(this_user)
        flash('Login successful.', 'success')
        return redirect(url_for('user.dashboard'))

    return render_template('auth/login.html', title='Log in', form=login_form)


@auth.route('/logout/')
def logout():
    logout_user()
    flash('Log out successful.', 'info')
    return redirect(url_for('auth.login'))

app/views/invite.py
from app import address, db
from app.forms import UserForm
from app.models import User, Invite
from app.utils import day_pref_to_binary, generate_invite_key

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import login_required

invite = Blueprint('invite', __name__, url_prefix='/invite/', template_folder='templates')


@invite.route('/', methods=['GET', 'POST'])
# @login_required
def index():
    user_form = UserForm()

    if user_form.validate_on_submit():
        partial_user = User(email=user_form.email.data,
                            full_name=user_form.full_name.data,
                            user_type=user_form.user_type.data,
                            join_date=user_form.join_date.data,
                            next_police_check=user_form.next_police_check.data,
                            time_pref=user_form.time_pref.data,
                            day_pref=day_pref_to_binary(user_form.day_prefs.data))

        db.session.add(partial_user)
        db.session.commit()

        key = generate_invite_key()
        new_invite = Invite(user_id=partial_user.id, key=key)

        db.session.add(new_invite)
        db.session.commit()

        flash('Invitation created. The user can register at: ' + address + '/register/' + key, 'success')
        return redirect(url_for('invite.index'))

    data = {
        'editing': False,
        'title': 'Invite User',
        'form': user_form
    }

    return render_template('user/invite.html', **data)


@invite.route('/<int:invite_id>/reissue/', methods=['GET', 'POST'])
@login_required
def reissue(invite_id):
    this_invite = Invite.query.filter_by(id=invite_id).scalar()

    if not this_invite:
        abort(404)

    new_key = generate_invite_key()
    this_invite.key = new_key

    db.session.commit()

    flash('Invite key reissued. The user must now register at: ' + address + '/register/' + new_key, 'success')
    return redirect(url_for('manage.index'))

app/views/job.py
from app import db
from app.forms import JobForm
from app.models import Job, OptIn

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import datetime

job = Blueprint('job', __name__, url_prefix='/job/', template_folder='templates')


@job.route('/', methods=['GET', 'POST'])
@login_required
def index():
    job_form = JobForm()

    if job_form.validate_on_submit():
        if job_form.date.data.weekday() == 6:
            flash('Date cannot fall on a Sunday.', 'danger')
            return redirect(url_for('job.index'))

        new_job = Job(user_id=current_user.id,
                      address=job_form.address.data,
                      date=job_form.date.data,
                      time=job_form.time.data,
                      notes=job_form.notes.data)

        db.session.add(new_job)
        db.session.commit()

        flash('Job created successfully.', 'success')
        return redirect(url_for('job.index'))

    data = {
        'editing': False,
        'title': 'Jobs',
        'form': job_form,
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'past_jobs': Job.query.filter(Job.date < datetime.date.today()).order_by(Job.date).all()
    }

    return render_template('job/index.html', **data)


@job.route('/<int:job_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    job_form = JobForm(obj=this_job)

    if job_form.validate_on_submit():
        job_form.populate_obj(this_job)
        db.session.commit()

        flash('Job edited.', 'success')
        return redirect(url_for('job.index'))

    return render_template('job/index.html', editing=True, title='Edit Job', form=job_form)


@job.route('/<int:job_id>/cancel/')
@login_required
def cancel(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    this_job.cancelled = not this_job.cancelled
    db.session.commit()

    if this_job.cancelled:
        flash('Job cancelled.', 'success')
    else:
        flash('Job un-cancelled.', 'success')

    return redirect(url_for('job.index'))


@job.route('/<int:job_id>/feedback/')
@login_required
def feedback(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_feedback = this_job.get_feedback(job_id)

    return render_template('job/feedback.html', title='Feedback For Address', job=this_job, all_feedback=all_feedback)


@job.route('/<int:job_id>/opt-in/')
@login_required
def opt_in(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    if this_job.cancelled:
        flash('Cannot opt-into/opt-out of a cancelled job.', 'danger')
        return redirect(url_for('user.roster'))

    this_opt_in = OptIn.query.filter_by(job_id=job_id, user_id=current_user.id).scalar()

    if this_opt_in:
        db.session.delete(this_opt_in)
        db.session.commit()

        flash('Opted-out.', 'success')
        return redirect(url_for('user.roster'))

    new_opt_in = OptIn(job_id=job_id, user_id=current_user.id)

    db.session.add(new_opt_in)
    db.session.commit()

    flash('Opted-in.', 'success')
    return redirect(url_for('user.roster'))


@job.route('/<int:job_id>/opt-ins/')
@login_required
def opt_ins(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_opt_ins = this_job.get_opt_ins(job_id)

    return render_template('job/opt_ins.html', title='Job #' + str(job_id) + ' Opt-ins', opt_ins=all_opt_ins)

app/views/user.py
from app import db
from app.forms import ChangePasswordForm, FeedbackForm, UserForm
from app.models import User, Job, Feedback
from app.utils import get_suitable_jobs

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import datetime

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/')
@user.route('/index/')
@user.route('/dashboard/')
@login_required
def dashboard():
    return render_template('user/dashboard.html', title='Dashboard')


@user.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    change_password_form = ChangePasswordForm()

    if change_password_form.validate_on_submit():
        this_user = User.query.filter_by(id=current_user.id).scalar()

        if not this_user.check_password(change_password_form.old_password.data):
            flash('Old password is incorrect.', 'danger')
            return redirect(url_for('user.profile'))

        this_user.set_password(change_password_form.new_password.data)
        db.session.commit()

        flash('Password changed.', 'success')
        return redirect(url_for('user.profile'))

    return render_template('user/profile.html', title=current_user.full_name, form=change_password_form)


@user.route('/roster/')
@login_required
def roster():
    jobs = Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all()

    data = {
        'title': 'Roster',
        'jobs': get_suitable_jobs(jobs, current_user.time_pref, current_user.day_pref)
    }

    return render_template('user/roster.html', **data)


@user.route('/feedback/', methods=['GET', 'POST'])
@login_required
def feedback():
    feedback_form = FeedbackForm()
    all_feedback = Feedback.query.filter_by(user_id=current_user.id).all()

    if feedback_form.validate_on_submit():
        new_feedback = Feedback(user_id=current_user.id,
                                job_id=feedback_form.job.data,
                                body=feedback_form.body.data)

        db.session.add(new_feedback)
        db.session.commit()

        flash('Feedback submitted.', 'success')
        return redirect(url_for('user.feedback'))

    data = {
        'title': 'Your Feedback',
        'form': feedback_form,
        'all_feedback': all_feedback
    }

    return render_template('user/feedback.html', **data)


@user.route('/user/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    this_user = User.query.filter_by(id=user_id).scalar()

    if not this_user:
        abort(404)

    user_form = UserForm(obj=this_user)

    if user_form.validate_on_submit():
        user_form.populate_obj(this_user)
        db.session.commit()

        flash('User edited.', 'success')
        return redirect(url_for('manage.index'))

    data = {
        'editing': True,
        'title': 'Edit User',
        'form': user_form
    }

    return render_template('user/edit.html', **data)

app/templates/user/dashboard.html
{% extends "_base.html" %}

{% block content %}
    <div class="row mb-4">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h3>{{ current_user.full_name }}</h3>
                    <a href="{{ url_for('user.profile') }}" class="btn btn-primary btn-block">View Profile</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong class="text-dark">Member since:</strong> {{ timestamp_pretty(current_user.join_date, show_time=False) }}</li>
                    <li class="list-group-item"><strong class="text-dark">Next police check:</strong> {{ timestamp_pretty(current_user.next_police_check, show_time=False) }}</li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header"><h3>Weather</h3></div>
                <div class="card-body">
                    <a href="https://www.accuweather.com/en/au/sydney/22889/weather-forecast/22889" class="aw-widget-legal">
                        <!--
                        By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at https://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at https://www.accuweather.com/en/privacy.
                        -->
                    </a>
                    <div id="awcc1525003331706" class="aw-widget-current" data-locationkey="22889" data-unit="c" data-language="en-us" data-useip="false" data-uid="awcc1525003331706"></div>
                    <script type="text/javascript" src="https://oap.accuweather.com/launch.js"></script>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-sm-4">
            <div class="card bg-light">
                <div class="card-body">
                    <a href="{{ url_for('user.roster') }}"><h3 class="card-title">Roster</h3></a>
                    <p class="card-text">View (and optionally opt-into) gardening jobs available to you.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card bg-light">
                <div class="card-body">
                    <a href="{{ url_for('user.feedback') }}"><h3 class="card-title">Feedback</h3></a>
                    <p class="card-text">View and submit feedback for past gardening jobs.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card bg-light">
                <div class="card-body">
                    <a href="{{ url_for('news.index') }}"><h3 class="card-title">News</h3></a>
                    <p class="card-text">View updates by Easy Care Gardening coordinators.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="card bg-light">
                <div class="card-body">
                    <a href="{{ url_for('auth.logout') }}"><h3 class="card-title">Log out</h3></a>
                    <p class="card-text">Keep your account safe by logging out when finished.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user/edit.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5 bg-light">
        <div class="card-header">
            <h2 class="mb-3">Edit User</h2>
        </div>
        <div class="card-body">
            {% include '_forms/user.html' %}
        </div>
    </div>
{% endblock %}

app/templates/user/feedback.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5 bg-light">
        <div class="card-header">
            <h2 class="mb-3">New Feedback</h2>
            <h5>You can only leave feedback for past jobs, which you can choose from below.</h5>
        </div>
        <div class="card-body">
            {% if form.job.choices %}
                <form action="{{ url_for('user.feedback') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group row">
                        {{ form.job.label(class_='col-sm-2 col-form-label') }}
                        <div class="col-sm-10">
                            {{ form.job(class_='form-control') }}
                            {% for error in form.job.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.body.label(class_='col-sm-2 col-form-label') }}
                        <div class="col-sm-10">
                            {{ form.body(class_='form-control') }}
                            {% for error in form.body.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {{ form.submit(class_='btn btn-primary float-right') }}
                </form>
            {% else %}
                No past jobs. Please try again later.
            {% endif %}
        </div>
    </div>
    <h2 class="mb-3">Your Feedback ({{ all_feedback|length }})</h2>
    {% for feedback in all_feedback %}
        <div class="card mb-3">
            <div class="card-body">
                <h3>{{ feedback.job.address }} on {{ timestamp_pretty(feedback.job.date, show_time=False) }}</h3>
                <p><i>Left on {{ timestamp_pretty(feedback.created_at) }}</i></p>
                <hr>
                <span>{{ feedback.body }}</span>
            </div>
        </div>
    {% else %}
        <p>No feedback.</p>
    {% endfor %}
{% endblock %}

app/templates/user/invite.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5 bg-light">
        <div class="card-header">
            <h2 class="mb-3">Invite User</h2>
            <h5>Ultimately generates an invite link that the user can use to set their password and register.</h5>
        </div>
        <div class="card-body">
            {% include '_forms/user.html' %}
        </div>
    </div>
{% endblock %}

app/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <h2 class="mb-3">Log in</h2>
    <div class="card mb-5 bg-light">
        <div class="card-body">
            <form action="{{ url_for('user.login') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group row">
                    {{ form.email.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.email(class_='form-control') }}
                        {% for error in form.email.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    {{ form.password.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.password(class_='form-control') }}
                        {% for error in form.password.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                {{ form.submit(class_='btn btn-primary float-right') }}
            </form>
        </div>
    </div>
    <h2><a href="{{ url_for('user.register') }}">Register</a></h2>
    <p>Accounts are granted upon request. To request an account, contact the administrator.</p>
{% endblock %}

app/templates/user/profile.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5">
        <div class="card-header">
            <h3>Profile</h3>
            <h5>Please contact an administrator to update your name, email, or availability.</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong class="text-dark">Email:</strong> {{ current_user.email }}</li>
            <li class="list-group-item"><strong class="text-dark">User type:</strong> {{ user_type_pretty(current_user.user_type) }}</li>
            <li class="list-group-item"><strong class="text-dark">Member since:</strong> {{ timestamp_pretty(current_user.join_date, show_time=False) }}</li>
            <li class="list-group-item"><strong class="text-dark">Next police check:</strong> {{ timestamp_pretty(current_user.next_police_check, show_time=False) }}</li>
            <li class="list-group-item"><strong class="text-dark">Availability:</strong>
                {{ time_pref_pretty(current_user.time_pref) }} on
                {% for day_pref in day_prefs_pretty(current_user.day_pref) %}
                    <span class="badge badge-pill badge-primary">{{ day_pref }}</span>
                {% else %}
                    <span class="badge badge-pill badge-warning">No days</span>
                {% endfor %}
            </li>
        </ul>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h3>Change Password</h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('user.profile') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group row">
                    {{ form.old_password.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.old_password(class_='form-control') }}
                        {% for error in form.old_password.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    {{ form.new_password.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.new_password(class_='form-control') }}
                        {% for error in form.new_password.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    {{ form.new_password_again.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.new_password_again(class_='form-control') }}
                        {% for error in form.new_password_again.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                {{ form.submit(class_='btn btn-primary float-right') }}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/user/roster.html
{% extends "_base.html" %}

{% block content %}
    <h2 class="mb-3">Available Jobs ({{ jobs|length }})</h2>
    {% for job in jobs %}
        {% with %}
            {% set cancelled = job.cancelled %}
            {% set changed = job.created_at != job.updated_at %}
            {% set opted_in = job.opted_into(current_user.id) %}
            <div class="card mb-3 {{ 'bg-danger' if cancelled }}{{ 'bg-warning' if changed }}">
                <div class="card-header {{ 'list-group-item-danger' if cancelled }} {{ 'list-group-item-warning' if changed }}">
                    {% if not cancelled %}
                        {% if opted_in %}
                            <a href="{{ url_for('job.opt_in', job_id=job.id) }}" class="btn btn-secondary mr-2">Opt-out</a>
                        {% else %}
                            <a href="{{ url_for('job.opt_in', job_id=job.id) }}" class="btn btn-primary mr-2">Opt-in</a>
                        {% endif %}
                        {% if changed %}
                            <strong>Attention!</strong> — This job was edited. If applicable, please double-check the new details and opt-in/opt-out if necessary.
                        {% endif %}
                    {% else %}
                        <strong>Attention!</strong> — This job has been cancelled.
                        {{ 'You have opted-in already so please do not attend.' if job.opted_into(current_user.id) else 'You cannot opt-into it.' }}
                    {% endif %}
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong class="text-dark">Address:</strong> {{ job.address }}</li>
                    <li class="list-group-item"><strong class="text-dark">Date:</strong> {{ timestamp_pretty(job.date, show_time=False) }}</li>
                    <li class="list-group-item"><strong class="text-dark">Time:</strong> {{ job.time }}</li>
                    {% if job.notes %}
                        <li class="list-group-item"><strong class="text-dark">Notes:</strong> {{ job.notes }}</li>
                    {% endif %}
                </ul>
            </div>
        {% endwith %}
    {% else %}
        <p>No available jobs.</p>
    {% endfor %}
{% endblock %}