app/views/news.py
from app import db
from app.forms import NewsForm
from app.models import NewsItem, NewsItemAcknowledgement

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required

news = Blueprint('news', __name__, url_prefix='/news/', template_folder='templates')


@news.route('/', methods=['GET', 'POST'])
@login_required
def index():
    news_form = NewsForm()

    if news_form.validate_on_submit():
        new_news = NewsItem(user_id=current_user.id, title=news_form.title.data, body=news_form.body.data)

        db.session.add(new_news)
        db.session.commit()

        flash('News item posted.', 'success')
        return redirect(url_for('news.index'))

    news_items = NewsItem.query.order_by(NewsItem.created_at).all()

    data = {
        'editing': False,
        'title': 'News',
        'form': news_form,
        'news_items': news_items
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    news_form = NewsForm(obj=news_item)

    if news_form.validate_on_submit():
        news_form.populate_obj(news_item)
        db.session.commit()

        flash('News item edited.', 'success')
        return redirect(url_for('news.index'))

    data = {
        'editing': True,
        'title': 'Edit News Item',
        'form': news_form,
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/delete/')
@login_required
def delete(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    db.session.delete(news_item)
    db.session.commit()

    flash('News item deleted.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledge/')
@login_required
def acknowledge(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    if news_item.is_acknowledged(current_user.id):
        flash('News item already acknowledged.', 'danger')
        return redirect(url_for('news.index'))

    new_acknowledgement = NewsItemAcknowledgement(user_id=current_user.id, news_item_id=news_item_id)

    db.session.add(new_acknowledgement)
    db.session.commit()

    flash('News item acknowledged.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledgements/', methods=['GET', 'POST'])
@login_required
def acknowledgements(news_item_id):
    all_acknowledgements = NewsItemAcknowledgement.query.filter_by(news_item_id=news_item_id).order_by(NewsItemAcknowledgement.created_at).all()

    data = {
        'acknowledgements': all_acknowledgements,
        'title': 'News Item #' + str(news_item_id) + ' Acknowledgments'
    }

    return render_template('news/acknowledgements.html', **data)

app/templates/news/_list.html
<div class="card mb-3">
    <div class="card-body">
        <h3>{{ news_item.title }}</h3>
        <p><i>Posted on {{ timestamp_pretty(news_item.created_at) }} by {{ news_item.author.full_name }}</i></p>
        <hr>
        <p>{{ news_item.body }}</p>
        <hr>
        {% if not news_item.is_acknowledged(current_user.id) %}
            <a href="{{ url_for('news.acknowledge', news_item_id=news_item.id) }}" class="btn btn-primary">Acknowledge</a>
        {% else %}
            <button class="btn btn-secondary" disabled>Acknowledged...</button>
        {% endif %}
        {% with n_cknowledgements = news_item.get_acknowledgements(news_item.id)|length %}
            <span class="text-muted ml-1">
                {% if n_cknowledgements == 0 %}
                    No acknowledgements
                {% else %}
                    <a href="{{ url_for('news.acknowledgements', news_item_id=news_item.id) }}">{{ n_cknowledgements }} acknowledgement(s)</a>
                {% endif %}
            </span>
        {% endwith %}
        <div class="btn-group float-right" role="group">
            <a href="{{ url_for('news.edit', news_item_id=news_item.id) }}" class="btn btn-warning">Edit</a>
            <a href="{{ url_for('news.delete', news_item_id=news_item.id) }}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>

app/templates/news/acknowledgements.html
{% extends "_base.html" %}

{% block content %}
    <h2 class="mb-3">
        <a href="{{ url_for('news.index') }}" class="btn btn-primary btn-lg mr-1">◄ Back to News</a>
        Acknowledgements ({{ acknowledgements|length }})
    </h2>
    {% for acknowledgement in acknowledgements %}
        <div class="card mb-3">
            <div class="card-body">
                ✅ Acknowledged by {{ acknowledgement.acknowledger.full_name }} on {{ timestamp_pretty(acknowledgement.created_at) }}
            </div>
        </div>
    {% else %}
        <p>No acknowledgements yet.</p>
    {% endfor %}
{% endblock %}

app/templates/news/form.html
<div class="card mb-5 bg-light">
    <div class="card-header">
        <h2 class="mb-3">{{ 'Edit' if editing else 'New' }} News Item</h2>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                {{ form.title.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.title(class_='form-control') }}
                    {% for error in form.title.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.body.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.body(class_='form-control') }}
                    {% for error in form.body.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            {% if editing %}
                {{ form.submit(class_='btn btn-primary float-right', value='Save Changes') }}
                <a href="{{ url_for('news.index') }}" class="btn btn-warning">Discard Changes</a>
            {% else %}
                {{ form.submit(class_='btn btn-primary float-right') }}
            {% endif %}
        </form>
    </div>
</div>

app/templates/news/index.html
{% extends "_base.html" %}

{% block content %}
    {% include '_forms/news.html' %}
    {% if not editing %}
        <h2 class="mb-3">All News Items ({{ news_items|length }})</h2>
        {% for news_item in news_items %}
            {% include 'news/_list.html' %}
        {% else %}
            <p>No news items.</p>
        {% endfor %}
    {% endif %}
{% endblock %}

app/templates/news/list.html
<div class="card mb-3">
    <div class="card-body">
        <h3>{{ news_item.title }}</h3>
        <p><i>Posted on {{ timestamp_pretty(news_item.created_at) }} by {{ news_item.author.full_name }}</i></p>
        <p>{{ news_item.body }}</p>
        {% if not news_item.is_acknowledged(current_user.id) %}
            <a href="{{ url_for('news.acknowledge', news_item_id=news_item.id) }}" class="btn btn-primary">Acknowledge</a>
        {% else %}
            <button class="btn btn-secondary" disabled>Acknowledged...</button>
        {% endif %}
        {% with n_cknowledgements = news_item.get_acknowledgements(news_item.id)|length %}
            <span class="text-muted ml-1">
                {% if n_cknowledgements == 0 %}
                    No acknowledgements
                {% else %}
                    <a href="{{ url_for('news.acknowledgements', news_item_id=news_item.id) }}">{{ n_cknowledgements }} acknowledgement(s)</a>
                {% endif %}
            </span>
        {% endwith %}
        <div class="btn-group float-right" role="group">
            <a href="{{ url_for('news.edit', news_item_id=news_item.id) }}" class="btn btn-warning">Edit</a>
            <a href="{{ url_for('news.delete', news_item_id=news_item.id) }}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>

app/templates/news/new.html
<div class="card mb-5 bg-light">
    <div class="card-header">
        <h2 class="mb-3">{{ 'Edit' if editing else 'New' }} News Item</h2>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                {{ form.title.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.title(class_='form-control') }}
                    {% for error in form.title.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.body.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.body(class_='form-control') }}
                    {% for error in form.body.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            {% if editing %}
                {{ form.submit(class_='btn btn-primary float-right', value='Save Changes') }}
                <a href="{{ url_for('news.index') }}" class="btn btn-warning">Discard Changes</a>
            {% else %}
                {{ form.submit(class_='btn btn-primary float-right') }}
            {% endif %}
        </form>
    </div>
</div>