app/views/auth.py
from app import db
from app.forms import RegistrationForm, LoginForm
from app.models import User, Invite

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import login_user, current_user, logout_user

auth = Blueprint('auth', __name__, template_folder='templates')


@auth.route('/register/<invite_key>', methods=['GET', 'POST'])
def register(invite_key):
    if current_user.is_authenticated:
        flash('You are already logged in.', 'info')
        return redirect(url_for('user.dashboard'))

    invite = Invite.query.filter_by(key=invite_key).scalar()

    if not invite:
        abort(404)

    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():
        invite.user.set_password(registration_form.password.data)

        db.session.delete(invite)
        db.session.commit()

        login_user(invite.user)
        flash('Registration successful.', 'success')
        return redirect(url_for('user.dashboard'))

    data = {
        'title': 'Register',
        'form': registration_form,
        'user': invite.user
    }

    return render_template('auth/register.html', **data)


@auth.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in.', 'info')
        return redirect(url_for('user.dashboard'))

    login_form = LoginForm()

    if login_form.validate_on_submit():
        this_user = User.query.filter_by(email=login_form.email.data).scalar()

        if this_user is None or not this_user.check_password(login_form.password.data):
            flash('Invalid credentials.', 'danger')
            return redirect(url_for('auth.login'))

        login_user(this_user)
        flash('Login successful.', 'success')
        return redirect(url_for('user.dashboard'))

    return render_template('auth/login.html', title='Log in', form=login_form)


@auth.route('/logout/')
def logout():
    logout_user()
    flash('Log out successful.', 'info')
    return redirect(url_for('auth.login'))

app/views/invite.py
from app import address, db
from app.forms import UserForm
from app.models import User, Invite
from app.utils import day_pref_to_binary, generate_invite_key

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import login_required

invite = Blueprint('invite', __name__, url_prefix='/invite/', template_folder='templates')


@invite.route('/', methods=['GET', 'POST'])
# @login_required
def index():
    user_form = UserForm()

    if user_form.validate_on_submit():
        partial_user = User(email=user_form.email.data,
                            full_name=user_form.full_name.data,
                            user_type=user_form.user_type.data,
                            join_date=user_form.join_date.data,
                            next_police_check=user_form.next_police_check.data,
                            time_pref=user_form.time_pref.data,
                            day_pref=day_pref_to_binary(user_form.day_prefs.data))

        db.session.add(partial_user)
        db.session.commit()

        key = generate_invite_key()
        new_invite = Invite(user_id=partial_user.id, key=key)

        db.session.add(new_invite)
        db.session.commit()

        flash('Invitation created. The user can register at: ' + address + '/register/' + key, 'success')
        return redirect(url_for('invite.index'))

    data = {
        'editing': False,
        'title': 'Invite User',
        'form': user_form
    }

    return render_template('user/invite.html', **data)


@invite.route('/<int:invite_id>/reissue/', methods=['GET', 'POST'])
@login_required
def reissue(invite_id):
    this_invite = Invite.query.filter_by(id=invite_id).scalar()

    if not this_invite:
        abort(404)

    new_key = generate_invite_key()
    this_invite.key = new_key

    db.session.commit()

    flash('Invite key reissued. The user must now register at: ' + address + '/register/' + new_key, 'success')
    return redirect(url_for('manage.index'))

app/views/job.py
from app import db
from app.forms import JobForm
from app.models import Job, OptIn

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import datetime

job = Blueprint('job', __name__, url_prefix='/job/', template_folder='templates')


@job.route('/', methods=['GET', 'POST'])
@login_required
def index():
    job_form = JobForm()

    if job_form.validate_on_submit():
        if job_form.date.data.weekday() == 6:
            flash('Date cannot fall on a Sunday.', 'danger')
            return redirect(url_for('job.index'))

        new_job = Job(user_id=current_user.id,
                      address=job_form.address.data,
                      date=job_form.date.data,
                      time=job_form.time.data,
                      notes=job_form.notes.data)

        db.session.add(new_job)
        db.session.commit()

        flash('Job created successfully.', 'success')
        return redirect(url_for('job.index'))

    data = {
        'editing': False,
        'title': 'Jobs',
        'form': job_form,
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'current_jobs': Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all(),
        'past_jobs': Job.query.filter(Job.date < datetime.date.today()).order_by(Job.date).all()
    }

    return render_template('job/index.html', **data)


@job.route('/<int:job_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    job_form = JobForm(obj=this_job)

    if job_form.validate_on_submit():
        job_form.populate_obj(this_job)
        db.session.commit()

        flash('Job edited.', 'success')
        return redirect(url_for('job.index'))

    return render_template('job/index.html', editing=True, title='Edit Job', form=job_form)


@job.route('/<int:job_id>/cancel/')
@login_required
def cancel(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    this_job.cancelled = not this_job.cancelled
    db.session.commit()

    if this_job.cancelled:
        flash('Job cancelled.', 'success')
    else:
        flash('Job un-cancelled.', 'success')

    return redirect(url_for('job.index'))


@job.route('/<int:job_id>/feedback/')
@login_required
def feedback(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_feedback = this_job.get_feedback(job_id)

    return render_template('job/feedback.html', title='Feedback For Address', job=this_job, all_feedback=all_feedback)


@job.route('/<int:job_id>/opt-in/')
@login_required
def opt_in(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    if this_job.cancelled:
        flash('Cannot opt-into/opt-out of a cancelled job.', 'danger')
        return redirect(url_for('user.roster'))

    this_opt_in = OptIn.query.filter_by(job_id=job_id, user_id=current_user.id).scalar()

    if this_opt_in:
        db.session.delete(this_opt_in)
        db.session.commit()

        flash('Opted-out.', 'success')
        return redirect(url_for('user.roster'))

    new_opt_in = OptIn(job_id=job_id, user_id=current_user.id)

    db.session.add(new_opt_in)
    db.session.commit()

    flash('Opted-in.', 'success')
    return redirect(url_for('user.roster'))


@job.route('/<int:job_id>/opt-ins/')
@login_required
def opt_ins(job_id):
    this_job = Job.query.filter_by(id=job_id).scalar()

    if not this_job:
        abort(404)

    all_opt_ins = this_job.get_opt_ins(job_id)

    return render_template('job/opt_ins.html', title='Job #' + str(job_id) + ' Opt-ins', opt_ins=all_opt_ins)

app/views/manage.py
from app import address
from app.forms import FindUserForm
from app.models import User, Invite

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import login_required

manage = Blueprint('manage', __name__, url_prefix='/manage/', template_folder='templates')


@manage.route('/', methods=['GET', 'POST'])
@login_required
def index():
    find_user_form = FindUserForm()

    if find_user_form.validate_on_submit():
        this_user = User.query.filter_by(email=find_user_form.email.data).scalar()

        if not this_user:
            flash('That user does not exist. You can create one with that email by clicking \'New Invite\' below, however.', 'warning')
            return redirect(url_for('manage.index'))

        return redirect(url_for('user.edit', user_id=this_user.id))

    invites = Invite.query.all()

    data = {
        'title': 'Manage',
        'form': find_user_form,
        'invites': invites,
        'address': address
    }

    return render_template('manage.html', **data)

app/views/news.py
from app import db
from app.forms import NewsForm
from app.models import NewsItem, NewsItemAcknowledgement

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required

news = Blueprint('news', __name__, url_prefix='/news/', template_folder='templates')


@news.route('/', methods=['GET', 'POST'])
@login_required
def index():
    news_form = NewsForm()

    if news_form.validate_on_submit():
        new_news = NewsItem(user_id=current_user.id, title=news_form.title.data, body=news_form.body.data)

        db.session.add(new_news)
        db.session.commit()

        flash('News item posted.', 'success')
        return redirect(url_for('news.index'))

    news_items = NewsItem.query.order_by(NewsItem.created_at).all()

    data = {
        'editing': False,
        'title': 'News',
        'form': news_form,
        'news_items': news_items
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    news_form = NewsForm(obj=news_item)

    if news_form.validate_on_submit():
        news_form.populate_obj(news_item)
        db.session.commit()

        flash('News item edited.', 'success')
        return redirect(url_for('news.index'))

    data = {
        'editing': True,
        'title': 'Edit News Item',
        'form': news_form,
    }

    return render_template('news/index.html', **data)


@news.route('/<int:news_item_id>/delete/')
@login_required
def delete(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    db.session.delete(news_item)
    db.session.commit()

    flash('News item deleted.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledge/')
@login_required
def acknowledge(news_item_id):
    news_item = NewsItem.query.filter_by(id=news_item_id).scalar()

    if not news_item:
        abort(404)

    if news_item.is_acknowledged(current_user.id):
        flash('News item already acknowledged.', 'danger')
        return redirect(url_for('news.index'))

    new_acknowledgement = NewsItemAcknowledgement(user_id=current_user.id, news_item_id=news_item_id)

    db.session.add(new_acknowledgement)
    db.session.commit()

    flash('News item acknowledged.', 'success')
    return redirect(url_for('news.index'))


@news.route('/<int:news_item_id>/acknowledgements/', methods=['GET', 'POST'])
@login_required
def acknowledgements(news_item_id):
    all_acknowledgements = NewsItemAcknowledgement.query.filter_by(news_item_id=news_item_id).order_by(NewsItemAcknowledgement.created_at).all()

    data = {
        'acknowledgements': all_acknowledgements,
        'title': 'News Item #' + str(news_item_id) + ' Acknowledgments'
    }

    return render_template('news/acknowledgements.html', **data)

app/views/user.py
from app import db
from app.forms import ChangePasswordForm, FeedbackForm, UserForm
from app.models import User, Job, Feedback
from app.utils import get_suitable_jobs

from flask import Blueprint, flash, redirect, url_for, render_template, abort
from flask_login import current_user, login_required
import datetime

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/')
@user.route('/index/')
@user.route('/dashboard/')
@login_required
def dashboard():
    return render_template('user/dashboard.html', title='Dashboard')


@user.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    change_password_form = ChangePasswordForm()

    if change_password_form.validate_on_submit():
        this_user = User.query.filter_by(id=current_user.id).scalar()

        if not this_user.check_password(change_password_form.old_password.data):
            flash('Old password is incorrect.', 'danger')
            return redirect(url_for('user.profile'))

        this_user.set_password(change_password_form.new_password.data)
        db.session.commit()

        flash('Password changed.', 'success')
        return redirect(url_for('user.profile'))

    return render_template('user/profile.html', title=current_user.full_name, form=change_password_form)


@user.route('/roster/')
@login_required
def roster():
    jobs = Job.query.filter(Job.date >= datetime.date.today()).order_by(Job.date).all()

    data = {
        'title': 'Roster',
        'jobs': get_suitable_jobs(jobs, current_user.time_pref, current_user.day_pref)
    }

    return render_template('user/roster.html', **data)


@user.route('/feedback/', methods=['GET', 'POST'])
@login_required
def feedback():
    feedback_form = FeedbackForm()
    all_feedback = Feedback.query.filter_by(user_id=current_user.id).all()

    if feedback_form.validate_on_submit():
        new_feedback = Feedback(user_id=current_user.id,
                                job_id=feedback_form.job.data,
                                body=feedback_form.body.data)

        db.session.add(new_feedback)
        db.session.commit()

        flash('Feedback submitted.', 'success')
        return redirect(url_for('user.feedback'))

    data = {
        'title': 'Your Feedback',
        'form': feedback_form,
        'all_feedback': all_feedback
    }

    return render_template('user/feedback.html', **data)


@user.route('/user/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    this_user = User.query.filter_by(id=user_id).scalar()

    if not this_user:
        abort(404)

    user_form = UserForm(obj=this_user)

    if user_form.validate_on_submit():
        user_form.populate_obj(this_user)
        db.session.commit()

        flash('User edited.', 'success')
        return redirect(url_for('manage.index'))

    data = {
        'editing': True,
        'title': 'Edit User',
        'form': user_form
    }

    return render_template('user/edit.html', **data)

app/templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{ title + ' — ' if title }}ECGV</title>
</head>
<body>
<div class="container mb-5">
    <div class="bg-light">
        <a href="{{ url_for('user.dashboard') if current_user.is_authenticated else url_for('auth.login') }}">
            <img src="{{ url_for('static', filename='logo.jpg') }}" class="img-fluid mx-auto d-block" alt="Easy Care Gardening Logo">
        </a>
        <h5 class="text-center mb-0 p-2"><strong>App Prototype</strong></h5>
    </div>
    {% if current_user.is_authenticated %}
        <ul class="nav justify-content-center mb-5 bg-light p-3">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.dashboard') }}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.profile') }}">Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.roster') }}">Roster</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.feedback') }}">Feedback</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('news.index') }}">News</a></li>
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                {{ user_type_pretty(current_user.user_type) }}
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Manage Job Sheets</a>
                <a class="dropdown-item" href="{{ url_for('news.index') }}">Manage News</a>
                <a class="dropdown-item" href="{{ url_for('job.index') }}">Manage Jobs</a>
                <a class="dropdown-item" href="#">Edit Job Sheet Template</a>
                <a class="dropdown-item" href="{{ url_for('manage.index') }}">Manage Users</a>
            </div>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
        </ul>
    {% endif %}
    <h1 class="mt-5 mb-5 text-center"><strong>{{ title if title or 'ECGV' }}</strong></h1>
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/acknowledgements.html
{% extends "base.html" %}

{% block content %}
<h2 class="mb-3">Acknowledgements ({{ acknowledgements|length }})
<a href="{{ url_for('news') }}" class="btn btn-primary btn-lg">Back to News</a></h2>
{% for acknowledgement in acknowledgements %}
<div class="card mb-3">
    <div class="card-body">
        ✅ Acknowledged by {{ acknowledgement.acknowledger.full_name }} on {{ timestamp_pretty(acknowledgement.created_at) }}
    </div>
</div>
{% else %}
<p>No acknowledgements yet.</p>
{% endfor %}
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{ title + ' — ' if title }}ECGV</title>
</head>
<body>
<div class="container mb-5">
    <div class="bg-light">
        <a href="{{ url_for('user.dashboard') if current_user.is_authenticated else url_for('user.login') }}">
            <img src="{{ url_for('static', filename='logo.jpg') }}" class="img-fluid mx-auto d-block" alt="Easy Care Gardening Logo">
        </a>
        <h5 class="text-center mb-0 p-2"><strong>App Prototype</strong></h5>
    </div>
    {% if current_user.is_authenticated %}
        <ul class="nav justify-content-center mb-5 bg-light p-3">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.dashboard') }}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.profile') }}">Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.roster') }}">Roster</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.feedback') }}">Feedback</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('news.index') }}">News</a></li>
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                {{ user_type_pretty(current_user.user_type) }}
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Manage Job Sheets</a>
                <a class="dropdown-item" href="{{ url_for('news.index') }}">Manage News</a>
                <a class="dropdown-item" href="{{ url_for('job.index') }}">Manage Jobs</a>
                <a class="dropdown-item" href="#">Edit Job Sheet Template</a>
                <a class="dropdown-item" href="{{ url_for('user.manage') }}">Manage Users</a>
            </div>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a></li>
        </ul>
    {% endif %}
    <h1 class="mt-5 mb-5 text-center"><strong>{{ title if title or 'ECGV' }}</strong></h1>
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="row mb-4">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <h3>{{ current_user.full_name }}</h3>
                <a href="{{ url_for('profile') }}" class="btn btn-primary btn-block">View Profile</a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong class="text-dark">Member since:</strong> {{ timestamp_pretty(current_user.join_date, show_time=False) }}</li>
                <li class="list-group-item"><strong class="text-dark">Next police check:</strong> {{ timestamp_pretty(current_user.next_police_check, show_time=False) }}</li>
            </ul>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header"><h3>Weather</h3></div>
            <div class="card-body">Placeholder...</div>
        </div>
    </div>
</div>
<div class="row mb-4">
    <div class="col-sm-4">
        <div class="card bg-light">
            <div class="card-body">
                <a href="{{ url_for('roster') }}"><h3 class="card-title">Roster</h3></a>
                <p class="card-text">View and opt-into gardening jobs available to you.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card bg-light">
            <div class="card-body">
                <a href="{{ url_for('feedback') }}"><h3 class="card-title">Feedback</h3></a>
                <p class="card-text">View and manage feedback regarding past jobs.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card bg-light">
            <div class="card-body">
                <a href="{{ url_for('news') }}"><h3 class="card-title">News</h3></a>
                <p class="card-text">View and manage updates by Easy Care Gardening coordinators.</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card bg-light">
            <div class="card-body">
                <a href="{{ url_for('jobs') }}"><h3 class="card-title">Manage Jobs</h3></a>
                <p class="card-text">View and manage the jobs a volunteer may opt-in to.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card bg-light">
            <div class="card-body">
                <a href="{{ url_for('logout') }}"><h3 class="card-title">Log out</h3></a>
                <p class="card-text">Keep your account safe by logging out when finished.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<h2 class="mb-3">Log in</h2>
<div class="card mb-5 bg-light">
    <div class="card-body">
        <form action="{{ url_for('login') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                {{ form.email.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.email(class_='form-control') }}
                    {% for error in form.email.errors %}
                    <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group row">
                {{ form.password.label(class_='col-sm-2 col-form-label') }}
                <div class="col-sm-10">
                    {{ form.password(class_='form-control') }}
                    {% for error in form.password.errors %}
                    <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            {{ form.submit(class_='btn btn-primary float-right') }}
        </form>
    </div>
</div>
<h2><a href="{{ url_for('register') }}">Register</a></h2>
<p>Accounts are granted upon request. To request an account, contact the administrator.</p>
{% endblock %}

app/templates/manage.html
{% extends "_base.html" %}

{% block content %}
    <div class="card mb-5 bg-light">
        <div class="card-header">
            <h2 class="mb-3">Find User</h2>
            <h5>Enter their email below to edit their details.</h5>
        </div>
        <div class="card-body">
            <form action="{{ url_for('manage.index') }}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group row">
                    {{ form.email.label(class_='col-sm-2 col-form-label') }}
                    <div class="col-sm-10">
                        {{ form.email(class_='form-control') }}
                        {% for error in form.email.errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                {{ form.submit(class_='btn btn-primary float-right') }}
            </form>
        </div>
    </div>
    <div class="card mb-5 bg-light">
        <div class="card-header">
            <h2 class="mb-3">
                <a href="{{ url_for('invite.index') }}" class="btn btn-primary btn-lg float-right">New Invite</a>
                Invites
            </h2>
            <h5>Users who have an invite link pending because they have not yet registered.</h5>
        </div>
        <ul class="list-group list-group-flush">
            {% for invite in invites %}
                <li class="list-group-item">
                    <a class="align-middle" href="{{ url_for('user.edit', user_id=invite.user.id) }}">{{ invite.user.full_name }} ({{ invite.user.email }})</a>
                    <div class="mt-3">
                        <a href="{{ url_for('invite.reissue', invite_id=invite.id) }}" class="btn btn-warning btn-sm mr-1">Re-issue</a>
                        <span class="text-muted" style="font-family: monospace">{{ address }}{{ invite.key }}</span>
                    </div>
                </li>
            {% else %}
                <li class="list-group-item">No invites.</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}